import type { Metadata } from "next";
import { Header } from "@/widgets/header";
import { FirstScreen } from "@/widgets/firstScreen";
import { Footer } from "@/widgets/footer";
import Providers from "./providers";
import "./styles/main.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: { width: "device-width", initialScale: 1 },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ru">
            <body>
                <Header />
                <FirstScreen />
                <Providers>{children}</Providers>
                <Footer />
            </body>
        </html>
    );
}
